services:
    postgres:
        image: postgres:17
        container_name: orchex
        restart: unless-stopped
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: orchex
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: