services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: orchex_app_dev
    restart: no
    ports:
      - "8080:8080"
      - "35729:35729"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orchex
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
      SPRING_DEVTOOLS_RESTART_POLL_INTERVAL: "2000"
      SPRING_DEVTOOLS_RESTART_QUIET_PERIOD: "1000"
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    container_name: orchex_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orchex
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d orchex"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  maven_cache: