package com.orchex.app.common.exception;

public enum ErrorCode {

    WORKFLOW_ALREADY_EXISTS,
    WORKFLOW_NOT_FOUND,
    WORKFLOW_EXECUTION_NOT_FOUND,
    WORKFLOW_TRIGGER_FAILED,
    TASK_EXECUTION_NOT_FOUND,
    TASK_EXECUTION_FAILED,
    TASK_HANDLER_NOT_FOUND,
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR
}
